bids-standard/bids-examples

ds008/participants.tsv

added sub-08 to ds008/participants.tsv

---

.travis.yml
eeg_matchingpennies/README

This should make #93 pass the test.

Fix eeg validator AND typofix

---

eeg_sleep/dataset_description.json
eeg_sleep/sub-01/eeg/sub-01_task-sleep_eeg.json

specifically, manufactureR vs. manufacturerS ...
ending with S is compliant with BIDS 1.1.1

fix version, fix field name

---

ds000247/sub-emptyroom/ses-18901015/sub-emptyroom_ses-18901015_scans.tsv

fixes #115 
there was a single acq_time that was not updated properly, this pr fixes that issue

fix single acq_time

---

README.md

fixes #53 
Next to the README updates in this PR, I made a new WIKI page for the iEEG data and formatted consistently between EEG, MEG, iEEG.
I think that potential visitors of this repo will now have a good idea what this is about.

link to main bids page, edit wiki link to home

---

eeg_ds000117/task-facerecognition_eeg.json

related to #132 
... just added "SoftwareFilters": "n/a" - and then called prettify for the JSON (indentation etc.)

add softwarefilters: n/a

---

README.md

genetics_ukbb added

---

README.md

This PR is to merge the newest version of BEP009 examples including an updated README.md file.

[ENH] merge newest version of BEP009 examples

---

7t_trt/task-rest_acq-fullbrain_bold.json
7t_trt/task-rest_acq-prefrontal_bold.json
eeg_face13/sub-001/eeg/sub-001_task-faceFO_coordsystem.json
eeg_face13/sub-002/eeg/sub-002_task-faceFO_coordsystem.json
eeg_face13/sub-003/eeg/sub-003_task-faceFO_coordsystem.json
eeg_face13/sub-004/eeg/sub-004_task-faceFO_coordsystem.json
eeg_face13/sub-005/eeg/sub-005_task-faceFO_coordsystem.json
eeg_face13/sub-006/eeg/sub-006_task-faceFO_coordsystem.json
eeg_face13/sub-007/eeg/sub-007_task-faceFO_coordsystem.json
eeg_face13/sub-008/eeg/sub-008_task-faceFO_coordsystem.json
eeg_face13/sub-009/eeg/sub-009_task-faceFO_coordsystem.json
eeg_face13/sub-010/eeg/sub-010_task-faceFO_coordsystem.json
ieeg_visual_multimodal/sub-som682/ses-somecog01/ieeg/sub-som682_ses-somecog01_task-spatialobject_run-01_ieeg.json
ieeg_visual_multimodal/sub-som682/ses-somecog01/ieeg/sub-som682_ses-somecog01_task-spatialobject_run-02_ieeg.json
ieeg_visual_multimodal/sub-som682/ses-somecog01/ieeg/sub-som682_ses-somecog01_task-spatialobject_run-03_ieeg.json
ieeg_visual_multimodal/sub-som682/ses-somecog01/ieeg/sub-som682_ses-somecog01_task-spatialobject_run-04_ieeg.json
ieeg_visual_multimodal/sub-som682/ses-somecog01/ieeg/sub-som682_ses-somecog01_task-spatialpattern_run-01_ieeg.json
ieeg_visual_multimodal/sub-som682/ses-somecog01/ieeg/sub-som682_ses-somecog01_task-spatialpattern_run-02_ieeg.json
ieeg_visual_multimodal/sub-som682/ses-somecog01/ieeg/sub-som682_ses-somecog01_task-spatialpattern_run-03_ieeg.json
ieeg_visual_multimodal/sub-som682/ses-somecog01/ieeg/sub-som682_ses-somecog01_task-spatialpattern_run-04_ieeg.json
ieeg_visual_multimodal/sub-som682/ses-somecog01/ieeg/sub-som682_ses-somecog01_task-temporalpattern_run-01_ieeg.json
ieeg_visual_multimodal/sub-som682/ses-somecog01/ieeg/sub-som682_ses-somecog01_task-temporalpattern_run-02_ieeg.json
ieeg_visual_multimodal/sub-som682/ses-somecog01/ieeg/sub-som682_ses-somecog01_task-temporalpattern_run-03_ieeg.json
ieeg_visual_multimodal/sub-som682/ses-somecog01/ieeg/sub-som682_ses-somecog01_task-temporalpattern_run-04_ieeg.json

I won't be able to solve all problems --- in particular those relating to Ephys coordsystems.
But I think this is a fair start and good enough to then release 1.4.0
@Andesha please see the fixes I made to your `eeg_face13` dataset
@irisgroen I removed your two fields:
-   "CogAtlasID": "n/a",
-    "CogPOID": "n/a",
if they are N/A, it's better to not name them at all --> these are optional fields and IF they are present, they must be formatted as a URI (for example, a https URL).
the eeg_rishikesh dataset will pass after https://github.com/bids-standard/bids-validator/pull/1110 is merged.

Fixes before release 1.4.0

---

ds000117/sub-01/ses-meg/meg/sub-01_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-02/ses-meg/meg/sub-02_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-03/ses-meg/meg/sub-03_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-04/ses-meg/meg/sub-04_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-05/ses-meg/meg/sub-05_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-06/ses-meg/meg/sub-06_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-07/ses-meg/meg/sub-07_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-08/ses-meg/meg/sub-08_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-09/ses-meg/meg/sub-09_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-10/ses-meg/meg/sub-10_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-11/ses-meg/meg/sub-11_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-12/ses-meg/meg/sub-12_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-13/ses-meg/meg/sub-13_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-14/ses-meg/meg/sub-14_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-15/ses-meg/meg/sub-15_ses-meg_task-facerecognition_coordsystem.json
ds000117/sub-16/ses-meg/meg/sub-16_ses-meg_task-facerecognition_coordsystem.json

@RikHenson
After merging, this fix should be reported to the OpenNeuro dataset:
https://openneuro.org/datasets/ds000117

ds000117: "Elekta/Neuromag" => "ElektaNeuromag"

---

CONTRIBUTING.md
README.md

closes #208 
for after 1.4 is released.

Readme improvements, find "dataset maintainer" for each dataset

---

ds000246/CHANGES
ds000246/README
ds000246/dataset_description.json
ds000246/sub-emptyroom/meg/sub-emptyroom_task-noise_run-01_meg.json

Minor metadata changes and organization to match what's on OpenNeuro ds000246

Minor metadata changes 

---

ds000247/CHANGES
ds000247/README
ds000247/dataset_description.json
ds000247/sub-0002/ses-0001/meg/sub-0002_ses-0001_task-rest_run-01_meg.json
ds000247/sub-0003/ses-0001/meg/sub-0003_ses-0001_task-rest_run-01_meg.json
ds000247/sub-0004/ses-0001/meg/sub-0004_ses-0001_task-rest_run-01_meg.json
ds000247/sub-0006/ses-0001/meg/sub-0006_ses-0001_task-rest_run-01_meg.json
ds000247/sub-0007/ses-0001/meg/sub-0007_ses-0001_task-rest_run-01_meg.json
ds000247/sub-emptyroom/ses-18901014/meg/sub-emptyroom_ses-18901014_task-noise_run-01_meg.json
ds000247/sub-emptyroom/ses-18901015/meg/sub-emptyroom_ses-18901015_task-noise_run-01_meg.json
ds000247/sub-emptyroom/ses-18910228/meg/sub-emptyroom_ses-18910228_task-noise_run-01_meg.json
ds000247/sub-emptyroom/ses-18910303/meg/sub-emptyroom_ses-18910303_task-noise_run-01_meg.json
ds000247/sub-emptyroom/ses-18910512/meg/sub-emptyroom_ses-18910512_task-noise_run-01_meg.json

Minor changes, related to metadata, creating a new line per keyword in json files, etc

Minor updates for ds000247

---

.github/workflows/validate_datasets.yml

closes #228 
not pretty, but it works

validate headers in synthetic ds

---

.github/workflows/validate_datasets.yml

testing the validation on different platforms, see: https://github.com/bids-standard/bids-examples/issues/229#issuecomment-774128242

run tests on all platforms

---

README.md

closes #243 (intended as a replacement)
closes #229 
@VisLab, I took your suggestions from #243 and tuned them a bit. I intend this PR as an extension/replacement of your PR.
Is that okay with you? Are there aspects that I missed in the changes proposed here?

DOC: add info on how to validate examples

---

asl001/README

Update README asl_001

---

eeg_hed_small/task-FacePerception_events.json

There was an error in the JSON file and I corrected.  Hopefully this will address the issue in the bids-validator PR1299.

Corrected the ? character error in the Description

---

.github/workflows/validate_datasets.yml

following https://github.com/bids-standard/bids-validator/pull/1349

update global install of bids-validator dev version

---

run_tests.sh

This will make it easier to test new features on the validator.
Also worked out the logic of this file and attempted to rewrite it to be clearer. Opening PR to make sure I didn't break things...

TEST: Allow VALIDATOR_ARGS to affect run_tests.sh behavior

---

eeg_matchingpennies/CHANGES
eeg_matchingpennies/README
eeg_matchingpennies/code/format_v020_to_v030.py
eeg_matchingpennies/dataset_description.json
eeg_matchingpennies/sub-05/eeg/sub-05_task-matchingpennies_events.tsv
eeg_matchingpennies/sub-06/eeg/sub-06_task-matchingpennies_events.tsv
eeg_matchingpennies/sub-07/eeg/sub-07_task-matchingpennies_events.tsv
eeg_matchingpennies/sub-08/eeg/sub-08_task-matchingpennies_events.tsv
eeg_matchingpennies/sub-09/eeg/sub-09_task-matchingpennies_events.tsv
eeg_matchingpennies/sub-10/eeg/sub-10_task-matchingpennies_events.tsv
eeg_matchingpennies/sub-11/eeg/sub-11_task-matchingpennies_events.tsv
eeg_matchingpennies/task-matchingpennies_events.json

The eeg_matchingpennies dataset cannot be very well re-used for several reasons:
- there are only 10 EEG electrodes recorded
- very few events were recorded
- ...
**However** it can still serve as a valuable example to showcase some BIDS principles.
That's why I want to add HED tags to it. I took a draft from @VisLab that she sent to me via email some months ago.
To use an HED tagging strategy, I re-formatted the dataset to some extend ... so that it uses a "trial based" events.tsv file again --> each row in events.tsv represents a trial, which contains several events.
What I am stuck at is how to format the brackets in the HED tags. This is the relevant part, I added linebreaks into the HED strings for readability:
```json
"trial_type": {
"Description": "Which hand was raised, and did …
```

Add HED tags to eeg_matchingpennies dataset

---

README.md

ASLBIDS examples were moved from google drive to OSF, links are updated on this page.

Update link asl example datasets

---

ds000248/dataset_description.json
ds116/dataset_description.json

[FIX] add Name to dataset_description

---

eeg_ds003654s_hed_library/dataset_description.json
eeg_ds003654s_hed_library/task-FacePerception_events.json

Updated score library version to fix issue #345

---

fnirs_automaticity/.bidsignore

Deals with part of: https://github.com/bids-standard/bids-examples/issues/352

Bidsignore fix

---

motion_spotrotation/sub-02/ses-body/sub-02_ses-body_scans.tsv
motion_spotrotation/sub-02/ses-joy/sub-02_ses-joy_scans.tsv

Fixing erroneously duplicated scans.tsv rows
See issue #367

[FIX] remove duplicated scans.tsv rows 

---

README.md
tools/print_dataset_listing.py

[FIX] fix typo

---

micr_SEMzarr/sub-01/ses-01/micr/sub-01_ses-01_sample-A_SPIM.json

Added mandatory sidecar file for ZARR file

---

README.md
tools/print_dataset_listing.py

Follow up to #434 to ensure that the script and most editors don't argue back and forth.

FIX: Update script to emit trailing newline, rerun

---

.github/workflows/deploy.yml
docs/README.md
docs/index.md
mkdocs.yml

- redirect to BIDS website
- make worklow work on dispatch only

[DOC] make BIDS example website redirect to main BIDS website

---

README.md
dataset_listing.tsv
tools/print_dataset_listing.py

Fixes failure in https://github.com/bids-standard/bids-website/pull/629.

doc: Add pheno004 to dataset listing
