bids-standard/bids-examples

eeg_sleep/sub-01/eeg/sub-01_task-sleep_eeg.json
this is bringing the sleep example to status quo of the BEP006 spec. Although this should still be reviewed by @ChristophePhillips, see #81
=> Adjust sleep

.travis.yml
This should fix the CI issue reported in https://github.com/bids-standard/bids-validator/issues/723#issuecomment-467333257
=> CI: Install bids-validator from npm over git

.travis.yml
fixes #156 
I am trying to ask Travis to check for file sizes now, blocking everything > 500kb.
=> Use Travis to block PRs with large files

README.md
This PR fixes #74, by making the documentation on available datasets more accessible and providing a table that shows (approximately) which modalities are present in each dataset.
Also fixes #154 to some extend, by adding all available links to the full data. The rest will have to be added by the respective dataset-authors later on.
The table is quite large although I tried hard to cut down on complexity. I would be very grateful for a review and some feedback.
Note that I also inserted a comment in the README, that we are interested in new examples **as long as** ... they cover some aspects that are not already covered. 
I don't see a point of hosting many datasets here if they are all the same in terms of their structure. Personally, I would even be up for cutting down on some example …
=> Migrating Documentation from WIKI to README

.github/workflows/validate_datasets.yml, README.md, ds000001-fmriprep/.bidsignore
This adds a `.SKIP_VALIDATION` file to the derivatives dataset, which will prevent the CI from evaluating it.
Once we want to reiterate on making the validator work for derivatives, a PR can be opened, the first commit being the remove of the `.SKIP_VALIDATION` file - then validation will work in that PR.
=> stop validating derivatives dataset until it works

asl004/sub-Sub1/perf/sub-Sub1_asl.json
Added TotalReadoutTime. In case of pe_polar, ASL analysis software required this information for asl as well. Therefore, we have added this in the example
=> added "TotalReadoutTime"

pet001/dataset_description.json, pet002/dataset_description.json, pet003/dataset_description.json, pet004/dataset_description.json, pet005/dataset_description.json
Fixing dataset_description for pet examples from https://github.com/bids-standard/bids-examples/pull/205#discussion_r604142005 @sappelhoff
=> Updated dataset_description in pet examples to be human readable

.github/workflows/validate_datasets.yml
this [new feature for GH actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency) may be helpful for the case where we open a PR to this repo **from** this repo (as oppposed to **from** a fork).
In those cases we had duplicate jobs running in the past, marked by "pull" and "push" --> with this feature, the duplicates should be cancelled.
Example of what we don't want anymore (screenshot):
see CI in https://github.com/bids-standard/bids-examples/pull/225
=> CI: auto-cancel duplicate CI jobs

ieeg_epilepsy/sub-01/ses-postimp/ieeg/sub-01_ses-postimp_task-seizure_run-01_ieeg.json, ieeg_epilepsy/sub-01/ses-postimp/ieeg/sub-01_ses-postimp_task-seizure_run-02_ieeg.json, ieeg_epilepsy/sub-01/ses-postimp/ieeg/sub-01_ses-postimp_task-seizure_run-03_ieeg.json, ieeg_epilepsy_ecog/sub-ecog01/ses-postimp/ieeg/sub-ecog01_ses-postimp_task-seizure_run-01_ieeg.json, ieeg_filtered_speech/sub-cm4/ieeg/sub-cm4_ieeg.json, ieeg_filtered_speech/sub-cm8/ieeg/sub-cm8_ieeg.json, ieeg_filtered_speech/sub-ir05/ieeg/sub-ir05_ieeg.json, ieeg_filtered_speech/sub-ir07/ieeg/sub-ir07_ieeg.json, ieeg_filtered_speech/sub-ir08/ieeg/sub-ir08_ieeg.json, ieeg_filtered_speech/sub-jh17/ieeg/sub-jh17_ieeg.json, ieeg_filtered_speech/sub-jh19/ieeg/sub-jh19_ieeg.json
cc @ftadel @dorahermes based on https://github.com/bids-standard/bids-specification/pull/799
I am removing the (in any case unused) DCOffsetCorrection field from some ieeg datasets. You may want to mirror these changes, if needed.
Also, please review and approve https://github.com/bids-standard/bids-specification/pull/799 ... or stop the process if you think it's going in the wrong direction.
=> ieeg: deprecate DCOffsetCorrection field

eeg_hed_small/dataset_description.json, eeg_hed_small/sub-002/eeg/sub-002_task-FacePerception_run-1_events.tsv, eeg_hed_small/sub-002/eeg/sub-002_task-FacePerception_run-2_events.tsv, eeg_hed_small/sub-002/eeg/sub-002_task-FacePerception_run-3_events.tsv, eeg_hed_small/sub-002/eeg/sub-002_task-FacePerception_run-4_events.tsv, eeg_hed_small/sub-002/eeg/sub-002_task-FacePerception_run-5_events.tsv, eeg_hed_small/sub-002/eeg/sub-002_task-FacePerception_run-6_events.tsv, eeg_hed_small/sub-003/eeg/sub-003_task-FacePerception_run-1_events.tsv, eeg_hed_small/sub-003/eeg/sub-003_task-FacePerception_run-2_events.tsv, eeg_hed_small/sub-003/eeg/sub-003_task-FacePerception_run-3_events.tsv, eeg_hed_small/sub-003/eeg/sub-003_task-FacePerception_run-4_events.tsv, eeg_hed_small/sub-003/eeg/sub-003_task-FacePerception_run-5_events.tsv, eeg_hed_small/sub-003/eeg/sub-003_task-FacePerception_run-6_events.tsv, eeg_hed_small/task-FacePerception_events.json
This example is now HED-3G compliant.  Bids validator version >= 1.8.2 is required.
=> Updated eeg_hed_small to be HED-3G compliant

pet001/dataset_description.json, pet003/dataset_description.json, pet004/dataset_description.json, pet005/dataset_description.json
closes #299 
I have checked ALS, qMRI and PET datasets and only the PET ones needed a BIDS version bump to be coherent with when the specification supported that data type.
=> [FIX] update pet datasets to 1.6 bids version

README.md
Changes fNIRS to NIRS as discussed in https://github.com/bids-standard/bids-specification/pull/1325
Note, the dataset descriptions themselves are not changed, as these are functional experiments. Hopefully we can get some datasets that are not functional in the near future.
=> Change fNIRS to NIRS

ds000001-fmriprep/desc-aparcaseg_dseg.tsv, ds000001-fmriprep/desc-aseg_dseg.tsv
Using the ds000001-fmriprep dataset for testing the new schema-based validator, we currently get:
```console
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ds000001-fmriprep                                                                                                                 │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
NOT_INCLUDED                               .SKIP_VALIDATION                                                                        
TSV_COLUMN_MISSING                         desc-aparcaseg_dseg.tsv                    Columns cited as index columns not in        
file: index. …
```
=> FIX: Add truncated dseg.tsv files for validation

.github/workflows/validate_datasets.yml
Incorporating updates to the HED validator resulted in a dependency on Node 18.
=> Require Node 18 for validation

eeg_ds003645s_hed/task-FacePerception_events.json, eeg_ds003645s_hed_inheritance/task-FacePerception_events.json, eeg_ds003645s_hed_library/task-FacePerception_events.json, eeg_ds003645s_hed_longform/task-FacePerception_events.json
There is one event file in the HED examples that has two event consecutive event markers at exactly the same time. The `trial` column in the example was annotated as a value column, resulting in duplicate tags when event marker annotations over multiple rows corresponding to the same time are combined.  
The trial information can be correctly incorporated using the curly brace notation, but the hed-javascript validator's handling of this feature is still under development as is the detecting of errors when multiple rows in the `events.tsv` file have the same onset values.
Both types of errors are now detected by the hed-python validator, so we realized the need to correct the examples.
=> Removed trial annotation from HED FacePerception_events.json example

README.md
Should help make sure it does not get too big?
=> [DOC] add repo size badge

7t_trt/participants.json, ds000117/participants.json, ds008/participants.json, ds009/participants.json, ds101/participants.json, ds102/participants.json, ds108/participants.json, ds110/participants.json, ds114/participants.json, ds116/participants.json, eeg_ds000117/participants.json
=> add participants.json with Levels as objects

.github/workflows/validate_datasets.yml, README.md, run_tests.sh
ATM it would complain that rc is not legit command due to all those spaces. Because no set -e used it just continues.
Also made it executable and adjusted shebang to be universaly working. There should be no need to invoke directly via bash -- shebang would do that
Script likely worked correctly anyways since there is explicit `exit $rc` so if `$rc` remained undefined and no failed validator runs, it was just `exit` - clean exit?
=> Fixup and enhance invocation of run_tests.sh

ds000246/participants.tsv, ieeg_epilepsy/participants.tsv, ieeg_epilepsyNWB/participants.tsv
A handy tool I discovered, to e.g. find all values which are not numeric
```
$ for f in */participants.tsv; do echo $f; mlr --itsv --otsv cut -f age $f; done
```
to just dump all the file names and their values for age if any
```
❯ mlr --itsv --otsv filter 'string($age) =~ "[^0-9]"' cut -f age ds000117/participants.tsv
participant_id	age	sex	first_ses
sub-emptyroom	n/a	n/a	n/a
```
to dump those which are not numeric in a particular file
=> Fix a few participants.tsv files

.github/workflows/validate_datasets.yml, run_tests.sh
Sits on top of #434 to have it correct here. Relevant to this PR changes are only to workflow
=> Add "master-deno" flavor of validator to use as well

.github/workflows/validate_datasets.yml
As of https://github.com/bids-standard/bids-validator/pull/1987, these should no longer raise errors.
=> Remove SKIP_VALIDATION from datasets the deno validator can handle

ieeg_epilepsy_ecog/dataset_description.json
I believe this the reason that https://github.com/bids-standard/bids-validator/pull/2014 is failing. In any case, there's no advantage to having optional keys with empty or invalid contents.
=> FIX: Remove empty/`n/a` entries from dataset_description.json

.github/workflows/validate_datasets.yml
Leave instructions for how to test on other branches of validator and/or specification.
=> CI: Simplify schema validator installation

ds001/CITATION.cff, ds001/dataset_description.json
=> [ENH] add citation.cff

.github/workflows/validate_datasets.yml
We were previously testing against the stable and dev versions of the NodeJS validator and only the dev version of the Deno validator.
This now tests against the stable and dev versions of the Deno validator and only the stable version of the NodeJS validator, reflecting the expectation that further development will be almost exclusively in the Deno validator.
=> CI: Test stable (deno), dev (deno) and legacy (node)

.github/workflows/validate_datasets.yml
The bids-validator is going to start diverging its `main` and `dev` branches. The idea with `main` is to continue to target the latest BIDS release, while `dev` will include changes proposed for upcoming releases.
=> ci: Test on both main and dev validator branches

7t_trt/participants.json
participants.tsv contains numeric values. The [Edinburgh Handedness Inventory](https://www.physio-pedia.com/Edinburgh_Handedness_Inventory_(EHI)) seems a likely source for these values. In any event, they do not match the BIDS default definition of "right", "left" and "ambidextrous".
=> fix(7t_trt): Define handedness column to match numeric values

run_tests.sh
There are some remaining issues for shellcheck but decided not to touch here.
=> Make possible to run on specified datasets, address some shellcheck concerns (quotes)

qmri_irt1/IRT1.json, qmri_irt1/derivatives/qMRLab/sub-01/anat/sub-01_M0map.json, qmri_irt1/derivatives/qMRLab/sub-01/anat/sub-01_T1map.json, qmri_mpm/derivatives/hmri/sub-01/anat/sub-01_MTsat.json, qmri_mpm/derivatives/hmri/sub-01/anat/sub-01_R1map.json, qmri_mpm/derivatives/hmri/sub-01/anat/sub-01_R2starmap.json, qmri_mtsat/derivatives/qMRLab/sub-01/anat/sub-01_M0map.json, qmri_mtsat/derivatives/qMRLab/sub-01/anat/sub-01_MTRmap.json, qmri_mtsat/derivatives/qMRLab/sub-01/anat/sub-01_MTsat.json, qmri_mtsat/derivatives/qMRLab/sub-01/anat/sub-01_T1map.json, qmri_mtsat/sub-01/anat/sub-01_flip-1_mt-off_MTS.json, qmri_mtsat/sub-01/anat/sub-01_flip-1_mt-on_MTS.json, qmri_mtsat/sub-01/anat/sub-01_flip-2_mt-off_MTS.json, qmri_sa2rage/sub-01/fmap/sub-01_flip-1_inv-1_TB1SRGE.json, qmri_sa2rage/sub-01/fmap/sub-01_flip-2_inv-2_TB1SRGE.json, qmri_tb1tfl/sub-01/fmap/sub-01_acq-anat_TB1TFL.json, qmri_tb1tfl/sub-01/fmap/sub-01_acq-famp_TB1TFL.json, qmri_vfa/VFA.json, qmri_vfa/derivatives/qMRLab/sub-01/anat/sub-01_M0map.json, qmri_vfa/derivatives/qMRLab/sub-01/anat/sub-01_T1map.json, qmri_vfa/derivatives/qMRLab/sub-01/fmap/sub-01_TB1map.json, qmri_vfa/sub-01/anat/sub-01_flip-1_VFA.json, qmri_vfa/sub-01/anat/sub-01_flip-2_VFA.json, qmri_vfa/sub-01/fmap/sub-01_acq-tr1_TB1AFI.json, qmri_vfa/sub-01/fmap/sub-01_acq-tr2_TB1AFI.json
After merging https://github.com/bids-standard/bids-specification/pull/2020, attempting to update the schema for the validator produces:
```
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ qmri_mtsat                                                                                                      │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
SIDECAR_KEY_REQUIRED -               /sub-01/anat/sub-01_flip-1_mt-off_MTS.ni                                    
RepetitionTimeExcitation             i.gz                                                                        
SIDECAR_KEY_REQUIRED -               /sub-01/anat/sub-01_flip-1_mt-on_MTS.nii …
```
=> fix: Update missing metadata to qMRI sequences

.github/workflows/validate_datasets.yml, pheno004/README.md, pheno004/dataset_description.json, pheno004/participants.json, pheno004/participants.tsv, pheno004/phenotype/ace.json, pheno004/phenotype/ace.tsv, pheno004/phenotype/demographics.json, pheno004/phenotype/demographics.tsv, pheno004/sub-01/anat/sub-01_T1w.json, pheno004/sub-02/anat/sub-02_T1w.json
Meant for the resolution of bids-spec PR 2044. This is a dataset containing a mismatch of subjects with MRI data and tabular phenotypic data to be considered a whole dataset of participants for the sake of the participants.tsv file.
=> Add pheno004 example dataset

xeeg_hed_score/README
The README now more clearly states where the sourcedata can be found, added a link to OpenNeuro.
=> Clarified in the README where sourcedata can be found 

.github/workflows/validate_datasets.yml
Installation can sometimes be slow and occasionally get a 429 Too Many Requests. A cache should help both things.
Bumping node to 22.
=> chore(ci): Cache npm packages

eeg_rishikesh/task-meditation_events.json, mrs_fmrs/participants.json
Working on improving column validation in the validator, we decided that failure to match declared column values should be an error, not a warning (https://github.com/bids-standard/bids-validator/pull/247). This produces errors in a couple examples, so this PR fixes those examples.
@arnodelorme You are listed as the maintainer of eeg_rishikesh
@markmikkelsen You are listed as the maintainer of mrs_fmrs
Would you mind reviewing these changes?
=> fix: Update column definitions that do not match column contents
